name: Download Ceph Docker Image

on:
  workflow_dispatch:

jobs:
  download:
    name: Download and Save Image as TAR
    runs-on: ubuntu-latest

    steps:
      - name: 🔧 Install skopeo
        run: |
          sudo apt update -y
          sudo apt install -y skopeo

      - name: 📦 Create output directory
        run: mkdir -p output

      - name: 📥 Pull and save ceph/ceph:v16 as TAR
        run: |
          IMAGE="ceph/ceph:v16"
          OUTPUT_PATH="output/ceph-v16.tar"
          echo "Downloading $IMAGE and saving as $OUTPUT_PATH"
          skopeo copy docker://$IMAGE docker-archive:$OUTPUT_PATH

      - name: 📤 Upload TAR file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ceph-v16-image
          path: output/ceph-v16.tar
